backend:
  name: github
  repo: JasperV/jasperv.github.io
  branch: master
  base_url: https://netlify-github-oauth.jasperv.nl/
publish_mode: editorial_workflow
media_folder: images
site_url: https://jasperv.nl
logo_url: https://jasperv.nl/img/logo.svg
collections:
  - label: 'Pages'
    name: 'Pages'
    files:
    - label: 'Index'
      name: 'Index'
      file: 'pages/index.json'
      fields:
        - { label: Title, name: title, widget: string }
