backend:
  name: github
  repo: JasperV/jasperv.github.io
  branch: master
  base_url: https://jasperv-netlify-github-oauth.herokuapp.com/

publish_mode: editorial_workflow

media_folder: images

collections:
  - label: 'Pages'
    name: 'Pages'
    files:
    - label: 'Index'
      name: 'Home'
      file: 'index.html'
      fields:
        - { label: Title, name: title, widget: string }
